<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
 
 
$routes->get('/', 'Home::index');
$routes->get('home', 'Home::index');
$routes->get('no_access/(:any)', 'NoAccess::index/$1');
$routes->get('home/logout', 'Home::logout');
$routes->get('login', 'Login::index');
$routes->post('login', 'Login::index');
$routes->get('qr/generate', 'Qr::generate');
$routes->post('login/google_login', 'Login::googleLogin');

// Customers
$routes->get('customers', 'Customers::index');

// Módulos placeholder (en desarrollo) - sin controlador completo
$routes->get('item_kits', 'ItemKits::index');
$routes->get('items', 'ModulePlaceholder::index');
$routes->get('sales', 'ModulePlaceholder::index');
$routes->get('suppliers', 'ModulePlaceholder::index');
$routes->get('receivings', 'ModulePlaceholder::index');
$routes->get('reports', 'Reports::index');
$routes->get('reports/registrosFecha', 'Reports::registrosFecha');
$routes->get('reports/ingresosFecha', 'Reports::ingresosFecha');
$routes->get('reports/porDoctor', 'Reports::porDoctor');
$routes->get('giftcards', 'ModulePlaceholder::index');
$routes->get('employees', 'Employees::index');
$routes->get('employees/view/(:num)', 'Employees::view/$1');
$routes->get('employees/view', 'Employees::view/-1');
$routes->post('employees/save/(:num)', 'Employees::save/$1');
$routes->post('employees/save/(:any)', 'Employees::save/-1');
$routes->post('employees/save', 'Employees::save');
$routes->post('employees/search', 'Employees::search');
$routes->post('employees/suggest', 'Employees::suggest');
$routes->post('employees/delete', 'Employees::delete');
$routes->get('config', 'Config::index');
$routes->get('config/backup', 'Config::backup');
$routes->post('config/save', 'Config::save');
$routes->post('config/savepoblacion', 'Config::savePoblacion');
$routes->get('config/deletepoblacion/(:num)', 'Config::deletePoblacion/$1');
$routes->get('seguridad', 'ModulePlaceholder::index');
$routes->get('seguridad_aforo', 'ModulePlaceholder::index');
$routes->get('controlcalidad', 'Controlcalidad::index');
$routes->get('controlcalidad/grafica/(:num)', 'Controlcalidad::grafica/$1');
$routes->post('controlcalidad/savecontrol', 'Controlcalidad::savecontrol');
$routes->post('controlcalidad/savevalor', 'Controlcalidad::savevalor');
$routes->get('reactivos', 'Reactivos::index');
$routes->get('reactivos/editar/(:num)', 'Reactivos::editar/$1');
$routes->get('reactivos/lotes/(:num)', 'Reactivos::lotes/$1');
$routes->post('reactivos/savereactivo', 'Reactivos::savereactivo');
$routes->post('reactivos/savelote', 'Reactivos::savelote');
$routes->post('reactivos/registrarsalida', 'Reactivos::registrarsalida');
$routes->post('reactivos/eliminar/(:num)', 'Reactivos::eliminar/$1');
$routes->get('equipos', 'Equipos::index');
$routes->get('equipos/detalle/(:num)', 'Equipos::detalle/$1');
$routes->post('equipos/saveequipo', 'Equipos::saveequipo');
$routes->post('equipos/savemantenimiento', 'Equipos::savemantenimiento');
$routes->get('auditoria', 'Auditoria::index');
$routes->get('doctors', 'Doctors::index');
$routes->get('labotests', 'Labotests::index');
$routes->get('labotests/view/(:num)', 'Labotests::view/$1');
$routes->get('labotests/view', 'Labotests::view/-1');
$routes->get('labotests/subview/(:num)', 'Labotests::subview/$1');
$routes->get('labotests/detail/(:num)', 'Labotests::detail/$1');
$routes->get('labotests/perfiles', 'Labotests::perfiles');
$routes->post('labotests/saveperfil', 'Labotests::saveperfil');
$routes->get('labotests/deleteperfil/(:num)', 'Labotests::deleteperfil/$1');
$routes->post('labotests/save/(:num)', 'Labotests::save/$1');
$routes->post('labotests/save/(:any)', 'Labotests::save/0');
$routes->post('labotests/save', 'Labotests::save');
$routes->post('labotests/savesubmain/(:num)', 'Labotests::savesubmain/$1');
$routes->post('labotests/savesub', 'Labotests::savesub');
$routes->post('labotests/savesecitem', 'Labotests::savesecitem');
$routes->post('labotests/orderSecItems', 'Labotests::orderSecItems');
$routes->post('labotests/saveformula', 'Labotests::saveFormula');
$routes->post('labotests/deleteformula/(:num)', 'Labotests::deleteFormula/$1');
$routes->get('labotests/duplicatesecitem/(:num)', 'Labotests::duplicatesecitem/$1');
$routes->get('labotests/deletecategory/(:num)', 'Labotests::deletecategory/$1');
$routes->get('labotests/deleteprianacategoria/(:num)', 'Labotests::deleteprianacategoria/$1');
$routes->get('labotests/manuales', 'Labotests::manualesIndex');
$routes->get('labotests/manuales/(:num)', 'Labotests::manuales/$1');
$routes->post('labotests/savemanual', 'Labotests::saveManual');
$routes->get('labotests/deletemanual/(:num)', 'Labotests::deleteManual/$1');
$routes->post('labotests/deletesecitem/(:num)', 'Labotests::deletesecitem/$1');
$routes->get('labotests/deletesecitem/(:num)', 'Labotests::deletesecitem/$1');
$routes->post('labotests/savepriresultado', 'Labotests::savepriresultado');
$routes->post('labotests/deletepriresultado/(:num)', 'Labotests::deletepriresultado/$1');
$routes->get('labotests/deletepriresultado/(:num)', 'Labotests::deletepriresultado/$1');
$routes->get('toquotes', 'Toquotes::index');
$routes->post('toquotes/savetoquotelog', 'Toquotes::savetoquotelog');
$routes->get('registers', 'Registers::index');
$routes->get('expediente', 'Expediente::index');
$routes->get('expediente/view/(:num)', 'Expediente::view/$1');
$routes->post('expediente/search', 'Expediente::search');
$routes->get('registers/lista', 'Registers::lista');
$routes->get('registers/view/(:num)', 'Registers::view/$1');
$routes->get('registers/viewreport/(:num)', 'Registers::viewreport/$1');
$routes->get('registers/pdf/(:num)', 'Registers::pdf/$1');
$routes->post('registers/save', 'Registers::save');
$routes->post('registers/validar', 'Registers::validar');
$routes->post('registers/crearmuestra', 'Registers::crearmuestra');
$routes->get('registers/cambiarestadomuestra/(:num)/(:num)', 'Registers::cambiarestadomuestra/$1/$2');
$routes->post('registers/search_paciente', 'Registers::searchPaciente');
$routes->post('registers/search_doctor', 'Registers::searchDoctor');
$routes->post('registers/search_prueba', 'Registers::searchPrueba');
$routes->post('registers/saveregvalues', 'Registers::saveregvalues');
$routes->post('registers/saveanalisiss', 'Registers::saveanalisiss');
$routes->post('registers/delete/(:num)', 'Registers::delete/$1');
$routes->post('registers/addpago/(:num)', 'Registers::addpago/$1');
$routes->get('registers/historial/(:num)', 'Registers::historial/$1');
$routes->get('customers/view/(:num)', 'Customers::view/$1');
$routes->get('customers/view', 'Customers::view/0');
$routes->post('customers/search', 'Customers::search');
$routes->post('customers/suggest', 'Customers::suggest');
$routes->post('customers/save/(:num)', 'Customers::save/$1');
$routes->post('customers/save/(:any)', 'Customers::save/-1');
$routes->post('customers/save', 'Customers::save');
$routes->post('customers/delete', 'Customers::delete');

// Doctors
$routes->get('doctors/view/(:num)', 'Doctors::view/$1');
$routes->get('doctors/view', 'Doctors::view/-1');
$routes->get('doctors/save/(:any)', 'Doctors::view/$1');
$routes->get('doctors/save', 'Doctors::view/-1');
$routes->post('doctors/search', 'Doctors::search');
$routes->post('doctors/suggest', 'Doctors::suggest');
$routes->post('doctors/saves/(:num)', 'Doctors::saves/$1');
$routes->post('doctors/save/(:any)', 'Doctors::saves/$1');
$routes->post('doctors/save', 'Doctors::saves');
$routes->post('doctors/delete', 'Doctors::delete');
