-- Actualización de manuales con datos REALES extraídos de insertos públicos en la web
-- Fuentes: access.wiener-lab.com, spinreact.com
-- EJECUTAR PRIMERO: seed_manuals_proveedores.sql

-- ============ PCR (Latex) / Proteína C Reactiva - Wiener Lab CRP hs ============
SET @pcr_manual = '<div class="manual-procedimiento"><h3>PCR (Proteína C Reactiva) - Wiener Lab - Resumen del insert</h3><p><strong>Proveedor:</strong> Wiener Lab (Argentina) - Línea Turbitest AA</p><p><strong>Código:</strong> 1009800, 1008100, 1009230, etc.</p><h4>1. Muestra requerida</h4><ul><li><strong>Tipo:</strong> Suero o plasma (heparina recomendada para plasma)</li><li><strong>Recolección:</strong> Manera habitual</li><li><strong>No usar:</strong> Muestras hemolizadas, lipémicas o contaminadas</li><li><strong>Estabilidad:</strong> 2 meses en refrigerador (2-10°C) o 3 años congelada (-20°C)</li></ul><h4>2. Reactivos (kit Wiener Lab)</h4><ul><li><strong>Reactivo A:</strong> Solución buffer glicina (20 ml, 22 ml o 30 ml según presentación)</li><li><strong>Reactivo B:</strong> Suspensión de partículas de látex con anticuerpos anti-CRP (20 ml, 22 ml o 30 ml)</li><li><strong>No provisto:</strong> PCR Calibrador en serie Turbitest AA de Wiener lab</li><li><strong>Almacenamiento:</strong> Refrigerador 2-10°C hasta fecha de vencimiento. No congelar.</li></ul><h4>3. Equipo necesario</h4><p>Analizador automático capaz de medir absorbancias a <strong>570 nm</strong>. Ej: Statfax, CT60i de Wiener lab.</p><h4>4. Procedimiento paso a paso (analizador automático)</h4><table class="table table-sm"><tr><th>Parámetro</th><th>Valor</th></tr><tr><td>Longitud de onda</td><td>570 nm</td></tr><tr><td>Temperatura</td><td>37°C</td></tr><tr><td>Volumen muestra</td><td>5 µl</td></tr><tr><td>Dilución muestra</td><td>1/4</td></tr><tr><td>Volumen Reactivo A</td><td>150 µl</td></tr><tr><td>Volumen Reactivo B</td><td>150 µl</td></tr><tr><td>Incubación (R1 + Muestra)</td><td>300 s (5 min)</td></tr><tr><td>Tiempo lectura</td><td>180 s</td></tr><tr><td>Calibración</td><td>6 puntos (calibradores 1, 3, 4, 5, 6, 7)</td></tr><tr><td>Rango de medición</td><td>0,2 - 100 mg/l</td></tr></table><h4>5. Valores de referencia</h4><p><strong>0 - 5 mg/l</strong></p><p>Cada laboratorio debe establecer sus propios intervalos.</p><h4>6. Observaciones</h4><p>Muestras con resultados elevados o procesos inflamatorios severos: diluir 1:5 ó 1:10 en solución fisiológica. No hay efecto prozona hasta 1000 mg/l.</p><p><em>Insert completo: access.wiener-lab.com (CRP hs Turbitest AA)</em></p></div>';

UPDATE dom_manuals SET `manual` = @pcr_manual WHERE prianacategoria_id = 80 AND (tittle LIKE '%Wiener Lab%Resumen%' OR tittle = 'PCR (Latex) - Wiener Lab: Resumen del insert') AND (deleted = 0 OR deleted IS NULL);

-- ============ Ferritina - SpinReact (Turbilatex) ============
SET @ferr_manual = '<div class="manual-procedimiento"><h3>Ferritina - SpinReact Turbilatex - Resumen del insert</h3><p><strong>Proveedor:</strong> SpinReact (España)</p><p><strong>Ref:</strong> TK1107140 (R1: 2x24 ml, R2: 1x12 ml, FERR-CAL: 1x3 ml)</p><h4>1. Muestra requerida</h4><ul><li><strong>Tipo:</strong> Suero o plasma fresco</li><li><strong>Estabilidad:</strong> 7 días a 2-8°C o 3 meses a -20°C</li><li><strong>No usar:</strong> Muestras altamente hemolizadas o lipémicas. Centrifugar si hay fibrina.</li></ul><h4>2. Reactivos (kit SpinReact)</h4><ul><li><strong>R1 Diluyente:</strong> Tampón Tris 20 mmol/L, pH 8,2. Conservante.</li><li><strong>R2 Látex:</strong> Partículas recubiertas con IgG conejo anti-ferritina humana, pH 8,2.</li><li><strong>FERR-CAL:</strong> Reconstituir con 3,0 mL agua destilada. Reposar 10 min a temperatura ambiente.</li><li><strong>Almacenamiento:</strong> 2-8°C hasta caducidad. No congelar (altera látex).</li></ul><h4>3. Equipo necesario</h4><p>Espectrofotómetro/fotómetro a <strong>546 nm</strong> (cubeta termostatizable 37°C). O analizador Spintech 240.</p><h4>4. Procedimiento paso a paso (Spintech 240)</h4><table class="table table-sm"><tr><th>Parámetro</th><th>Valor</th></tr><tr><td>Longitud de onda</td><td>546 nm</td></tr><tr><td>Volumen muestra</td><td>18 µL</td></tr><tr><td>Volumen R1</td><td>160 µL</td></tr><tr><td>Volumen R2</td><td>40 µL</td></tr><tr><td>Tipo lectura</td><td>Endpoint</td></tr><tr><td>Calibración</td><td>Spline, 6 puntos</td></tr><tr><td>Rango de medida</td><td>Hasta 600 µg/L (diluir 1/5 si superior)</td></tr><tr><td>Límite detección</td><td>5,04 µg/L</td></tr></table><h4>5. Valores de referencia</h4><p><strong>Hombres:</strong> 30 – 220 µg/L</p><p><strong>Mujeres:</strong> 20 – 110 µg/L</p><h4>6. Observaciones</h4><p>Estandarizado frente al 3º Estándar Internacional de Ferritina. Calibración estable 30 días. Sin efecto prozona hasta 9000 µg/L. Lípidos 2,5 g/L o más interfieren.</p><p><em>Insert: spinreact.com (Turbilatex Ferritin TKTLIS44)</em></p></div>';

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted)
SELECT 28, 'Ferritina - SpinReact: Resumen del insert', @ferr_manual, 0
FROM (SELECT 1) AS d
WHERE NOT EXISTS (SELECT 1 FROM dom_manuals m WHERE m.prianacategoria_id = 28 AND m.tittle = 'Ferritina - SpinReact: Resumen del insert' AND COALESCE(m.deleted, 0) = 0);

-- ============ Glicemia - Human (GOD-POD típico) ============
SET @gluc_manual = '<div class="manual-procedimiento"><h3>Glicemia - Human - Procedimiento con Statfax</h3><p><strong>Proveedor:</strong> Human (Alemania)</p><h4>1. Muestra requerida</h4><ul><li><strong>Tipo:</strong> Suero (tubo rojo sin aditivo)</li><li><strong>Volumen:</strong> 1-2 ml máx. Dejar coagular 30 min y centrifugar.</li></ul><h4>2. Reactivos (kit Human Glucosa)</h4><ul><li><strong>Método:</strong> GOD-POD (Glucosa Oxidasa - Peroxidasa)</li><li><strong>Composición típica:</strong> Glucosa oxidasa, peroxidasa, 4-aminofenazona, fenol, buffer TRIS pH 7,4</li><li><strong>Almacenamiento:</strong> 2-8°C. Estable hasta caducidad.</li></ul><h4>3. Equipo</h4><p><strong>Statfax</strong> o analizador semiautomático. Fotómetro a 505 nm (o 500 nm).</p><h4>4. Procedimiento paso a paso</h4><ol><li><strong>Paso 1:</strong> Dejar coagular 30 min. Centrifugar. Obtener suero.</li><li><strong>Paso 2:</strong> Guardar suero en eppendorf. Rotular con código del sistema y fecha.</li><li><strong>Paso 3:</strong> Pipetear <strong>1 ml de reactivo Human</strong> + <strong>10 µL de muestra</strong>. Incubar a <strong>37°C por 5 minutos</strong>.</li><li><strong>Paso 4:</strong> Registrar blancos y valores en Statfax. Longitud de onda <strong>505 nm</strong>.</li></ol><h4>5. Valores de referencia</h4><p>Ayuno: 70-100 mg/dL (3,9-5,6 mmol/L). Según rangos del laboratorio.</p><h4>6. Observaciones</h4><p>Verificar en cada lote: volúmenes y parámetros del programa Statfax según insert del kit Human recibido.</p></div>';

UPDATE dom_manuals SET `manual` = @gluc_manual WHERE prianacategoria_id = 44 AND (tittle LIKE '%Human%Statfax%' OR tittle LIKE '%Human%Uso con Statfax%') AND (deleted = 0 OR deleted IS NULL);
