-- Manuales completos - Quimica y Serologia
-- DELETE + INSERT con valores directos (sin variables)
-- Ejecutar TODO el archivo en phpMyAdmin o: mysql -u user -p laboratorio < manuales_completos.sql

DELETE FROM dom_manuals;

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (80, 'PCR (Latex) - Wiener Lab', '<div class="manual-procedimiento"><h3>PCR - Wiener Lab Turbitest AA</h3><p><strong>Proveedor:</strong> Wiener Lab (Argentina). Cod: 1009800, 1008100, 1009230</p><h4>1. Muestra</h4><ul><li><strong>Tipo:</strong> Suero o plasma (heparina para plasma)</li><li><strong>Estabilidad:</strong> 2 meses 2-10C o 3 anos -20C</li><li><strong>No usar:</strong> Hemolizadas, lipemicas, contaminadas</li></ul><h4>2. Reactivos</h4><ul><li><strong>R1:</strong> Buffer glicina. R2: Latex anti-CRP</li><li><strong>Almacenar:</strong> 2-10C. No congelar</li><li><strong>Calibrador:</strong> PCR Calibrador serie Turbitest AA (1,3,4,5,6,7)</li></ul><h4>3. Equipo</h4><p>Analizador 570 nm. Statfax, CT60i.</p><h4>4. Procedimiento</h4><p>Longitud onda 570 nm. Temp 37C. Muestra 5 ul dilucion 1/4. R1 150 ul. R2 150 ul. Incubacion R1+Muestra 300 s. Lectura 180 s. Calibracion 6 puntos.</p><h4>5. Rango medicion</h4><p>0,2 - 100 mg/l</p><h4>6. Valores referencia</h4><p>0 - 5 mg/l</p><h4>7. Observaciones</h4><p>Resultados elevados: diluir 1:5 o 1:10 en solucion fisiologica.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (28, 'Ferritina - SpinReact', '<div class="manual-procedimiento"><h3>Ferritina - SpinReact Turbilatex</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref TK1107140</p><h4>1. Muestra</h4><ul><li><strong>Tipo:</strong> Suero o plasma fresco</li><li><strong>Estabilidad:</strong> 7 dias 2-8C o 3 meses -20C</li><li><strong>Centrifugar</strong> si hay fibrina. No usar hemolizadas o lipemicas</li></ul><h4>2. Reactivos</h4><ul><li><strong>R1:</strong> Tampon Tris 20 mmol/L pH 8,2</li><li><strong>R2:</strong> Latex anti-ferritina humana pH 8,2</li><li><strong>FERR-CAL:</strong> Reconstituir con 3 mL agua destilada. Reposar 10 min</li><li><strong>Almacenar:</strong> 2-8C. No congelar</li></ul><h4>3. Equipo</h4><p>Espectrofotometro 546 nm. Spintech 240.</p><h4>4. Procedimiento</h4><p>Muestra 18 uL. R1 160 uL. R2 40 uL. Lectura endpoint. Calibracion Spline 6 puntos.</p><h4>5. Rango y referencia</h4><p>Hasta 600 ug/L. Diluir 1/5 si superior. Hombres 30-220 ug/L. Mujeres 20-110 ug/L.</p><h4>6. Observaciones</h4><p>Limite deteccion 5 ug/L. Sin prozona hasta 9000 ug/L. Lipidos 2,5 g/L o mas interfieren.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (28, 'Ferritina - Wiener Lab', '<div class="manual-procedimiento"><h3>Ferritina - Wiener Lab Turbitest</h3><p><strong>Proveedor:</strong> Wiener Lab (Argentina)</p><h4>1. Muestra</h4><ul><li>Suero o plasma. 7 dias 2-8C. 3 meses -20C</li><li>Evitar hemolisis y lipemia</li></ul><h4>2. Reactivos</h4><ul><li>R1: Buffer. R2: Latex anti-ferritina</li><li>Calibrador serie Turbitest</li><li>2-10C. No congelar</li></ul><h4>3. Equipo</h4><p>Analizador 540-570 nm. 37C</p><h4>4. Procedimiento</h4><p>Metodo inmunoturbidimetrico. Muestra + R1 + R2. Incubar. Lectura cinetica o endpoint.</p><h4>5. Valores referencia</h4><p>Hombres 30-300 ng/mL. Mujeres 15-150 ng/mL</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (44, 'Glicemia - Human', '<div class="manual-procedimiento"><h3>Glicemia - Human GOD-POD</h3><p><strong>Proveedor:</strong> Human (Alemania)</p><h4>1. Muestra</h4><ul><li><strong>Tipo:</strong> Suero. Tubo rojo sin aditivo. 1-2 ml</li><li><strong>Proceder:</strong> Coagular 30 min. Centrifugar. Obtener suero</li></ul><h4>2. Reactivos</h4><ul><li><strong>Metodo:</strong> GOD-POD (Glucosa Oxidasa - Peroxidasa)</li><li>Glucosa oxidasa, peroxidasa, 4-aminofenazona, fenol, buffer TRIS pH 7,4</li><li>2-8C hasta caducidad</li></ul><h4>3. Equipo</h4><p>Statfax o analizador. 505 nm (500 nm)</p><h4>4. Procedimiento</h4><ol><li>Pipetear 1 ml reactivo en tubo o cubeta</li><li>Incubar 37C 5 min</li><li>Agregar 10 uL muestra. Mezclar</li><li>Incubar 37C 5 min</li><li>Leer absorbancia 505 nm vs blanco reactivo</li></ol><h4>5. Valores referencia</h4><p>Ayuno: 70-100 mg/dL (3,9-5,6 mmol/L)</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (44, 'Glicemia - Wiener Lab', '<div class="manual-procedimiento"><h3>Glicemia - Wiener Lab</h3><p><strong>Proveedor:</strong> Wiener Lab (Argentina). Metodo GOD-PAP</p><h4>1. Muestra</h4><ul>Suero o plasma. Tubo sin anticoagulante o heparina. Coagular 30 min. Centrifugar.</ul><h4>2. Reactivos</h4><ul><li>R1: Buffer + enzimas. R2: Cromogeno</li><li>2-8C. Proteger de luz</li></ul><h4>3. Equipo</h4><p>Analizador 505-546 nm. 37C</p><h4>4. Procedimiento</h4><p>R1 + muestra. Incubar 5 min 37C. R2. Incubar 5 min. Lectura 505 nm.</p><h4>5. Referencia</h4><p>Ayuno 70-100 mg/dL</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (36, 'Creatinina - Human', '<div class="manual-procedimiento"><h3>Creatinina - Metodo Jaffe Cinetico</h3><p><strong>Proveedor:</strong> Human / Wiener Lab / Randox</p><h4>1. Muestra</h4><ul><li>Suero o plasma heparinizado. 0,1 ml (100 uL)</li><li>Estable 7 dias 2-8C</li></ul><h4>2. Reactivos</h4><ul><li><strong>Principio:</strong> Creatinina + acido picrico en medio alcalino</li><li>Reactivo picrato 55 mM + carbonato/NaOH. Reactivo trabajo: mezclar partes iguales</li><li>2-8C</li></ul><h4>3. Equipo</h4><p>Analizador 505-546 nm. 37C</p><h4>4. Procedimiento</h4><ol><li>1,0 ml reactivo trabajo en cubeta</li><li>0,1 ml muestra (100 uL)</li><li>Mezclar. Lectura cinetica 20 s y 80 s (delta A)</li></ol><h4>5. Longitud onda</h4><p>505-546 nm</p><h4>6. Referencia</h4><p>Hombres 0,7-1,3 mg/dL. Mujeres 0,6-1,1 mg/dL</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (36, 'Creatinina - Wiener Lab', '<div class="manual-procedimiento"><h3>Creatinina - Metodo Jaffe Cinetico</h3><p><strong>Proveedor:</strong> Human / Wiener Lab / Randox</p><h4>1. Muestra</h4><ul><li>Suero o plasma heparinizado. 0,1 ml (100 uL)</li><li>Estable 7 dias 2-8C</li></ul><h4>2. Reactivos</h4><ul><li><strong>Principio:</strong> Creatinina + acido picrico en medio alcalino</li><li>Reactivo picrato 55 mM + carbonato/NaOH. Reactivo trabajo: mezclar partes iguales</li><li>2-8C</li></ul><h4>3. Equipo</h4><p>Analizador 505-546 nm. 37C</p><h4>4. Procedimiento</h4><ol><li>1,0 ml reactivo trabajo en cubeta</li><li>0,1 ml muestra (100 uL)</li><li>Mezclar. Lectura cinetica 20 s y 80 s (delta A)</li></ol><h4>5. Longitud onda</h4><p>505-546 nm</p><h4>6. Referencia</h4><p>Hombres 0,7-1,3 mg/dL. Mujeres 0,6-1,1 mg/dL</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (50, 'Urea - Human', '<div class="manual-procedimiento"><h3>Urea - Metodo Enzimatico</h3><p><strong>Proveedor:</strong> Human / Wiener / SpinReact</p><h4>1. Muestra</h4><ul><li>Suero o plasma heparinizado. Evitar fluoruro y oxalato</li><li>10 uL muestra</li></ul><h4>2. Reactivos</h4><ul><li><strong>R1:</strong> TRIS pH 7,8, alfa-cetoglutarato, ureasa, GLDH</li><li><strong>R2:</strong> NADH. RT: 4 vol R1 + 1 vol R2 (estable 1 mes 2-8C)</li></ul><h4>3. Equipo</h4><p>Analizador 340 nm. 37C</p><h4>4. Procedimiento</h4><ol><li>1,0 ml reactivo trabajo en cubeta</li><li>10 uL muestra</li><li>Leer A1 a 30 s y A2 a 90 s. delta A = A1 - A2</li></ol><h4>5. Calculo</h4><p>delta A muestra / delta A patron x [patron] = mg/dL urea</p><h4>6. Referencia</h4><p>15-40 mg/dL. Si mayor 530 diluir 1/2</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (50, 'Urea - Wiener Lab', '<div class="manual-procedimiento"><h3>Urea - Metodo Enzimatico</h3><p><strong>Proveedor:</strong> Human / Wiener / SpinReact</p><h4>1. Muestra</h4><ul><li>Suero o plasma heparinizado. Evitar fluoruro y oxalato</li><li>10 uL muestra</li></ul><h4>2. Reactivos</h4><ul><li><strong>R1:</strong> TRIS pH 7,8, alfa-cetoglutarato, ureasa, GLDH</li><li><strong>R2:</strong> NADH. RT: 4 vol R1 + 1 vol R2 (estable 1 mes 2-8C)</li></ul><h4>3. Equipo</h4><p>Analizador 340 nm. 37C</p><h4>4. Procedimiento</h4><ol><li>1,0 ml reactivo trabajo en cubeta</li><li>10 uL muestra</li><li>Leer A1 a 30 s y A2 a 90 s. delta A = A1 - A2</li></ol><h4>5. Calculo</h4><p>delta A muestra / delta A patron x [patron] = mg/dL urea</p><h4>6. Referencia</h4><p>15-40 mg/dL. Si mayor 530 diluir 1/2</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (59, 'Colesterol - Human', '<div class="manual-procedimiento"><h3>Colesterol - Metodo CHOD-PAP</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. Ayuno 12 h. 10 uL</ul><h4>2. Reactivos</h4><ul><li>Esterasa, oxidasa, peroxidasa, 4-aminofenazona, fenol</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 1 ml + 10 uL muestra. 37C 10 min. Lectura 505 nm.</p><h4>4. Referencia</h4><p>Deseable menor 200 mg/dL. Limite 200-239. Alto 240 o mas</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (38, 'Colesterol - Wiener Lab', '<div class="manual-procedimiento"><h3>Colesterol - Metodo CHOD-PAP</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. Ayuno 12 h. 10 uL</ul><h4>2. Reactivos</h4><ul><li>Esterasa, oxidasa, peroxidasa, 4-aminofenazona, fenol</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 1 ml + 10 uL muestra. 37C 10 min. Lectura 505 nm.</p><h4>4. Referencia</h4><p>Deseable menor 200 mg/dL. Limite 200-239. Alto 240 o mas</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (49, 'Trigliceridos - Human', '<div class="manual-procedimiento"><h3>Trigliceridos - Metodo GPO-PAP</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. Ayuno 12 h. 10 uL</ul><h4>2. Reactivos</h4><ul><li>Lipasa, GK, GPO, peroxidasa, 4-AF, 4-clorofenol</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 1 ml + 10 uL muestra. 37C 10 min. Lectura 505 nm.</p><h4>4. Referencia</h4><p>Normal menor 150 mg/dL. Alto 150-499. Muy alto 500 o mas</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (58, 'Trigliceridos - Wiener Lab', '<div class="manual-procedimiento"><h3>Trigliceridos - Metodo GPO-PAP</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. Ayuno 12 h. 10 uL</ul><h4>2. Reactivos</h4><ul><li>Lipasa, GK, GPO, peroxidasa, 4-AF, 4-clorofenol</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 1 ml + 10 uL muestra. 37C 10 min. Lectura 505 nm.</p><h4>4. Referencia</h4><p>Normal menor 150 mg/dL. Alto 150-499. Muy alto 500 o mas</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (42, 'GOT - Human', '<div class="manual-procedimiento"><h3>GOT (AST) - Metodo IFCC</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. Evitar hemolisis. 20 uL</ul><h4>2. Reactivos</h4><ul><li>L-aspartato, alfa-cetoglutarato, LDH, NADH, Tris pH 7,8</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 500 uL + 20 uL muestra. Incubar 5 min 37C. R2 100 uL. Lectura cinetica 340 nm cada 60 s durante 3 min.</p><h4>4. Referencia</h4><p>Hombres menor 40 U/L. Mujeres menor 32 U/L</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (64, 'GOT/AST - Wiener Lab', '<div class="manual-procedimiento"><h3>GOT (AST) - Metodo IFCC</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. Evitar hemolisis. 20 uL</ul><h4>2. Reactivos</h4><ul><li>L-aspartato, alfa-cetoglutarato, LDH, NADH, Tris pH 7,8</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 500 uL + 20 uL muestra. Incubar 5 min 37C. R2 100 uL. Lectura cinetica 340 nm cada 60 s durante 3 min.</p><h4>4. Referencia</h4><p>Hombres menor 40 U/L. Mujeres menor 32 U/L</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (41, 'GPT - Human', '<div class="manual-procedimiento"><h3>GPT (ALT) - Metodo IFCC</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. 20 uL</ul><h4>2. Reactivos</h4><ul><li>L-alanina, alfa-cetoglutarato, LDH, NADH</li></ul><h4>3. Procedimiento</h4><p>R1 500 uL + 20 uL muestra. R2 100 uL. Cinetica 340 nm 37C.</p><h4>4. Referencia</h4><p>Hombres menor 41 U/L. Mujeres menor 33 U/L</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (41, 'GPT - Wiener Lab', '<div class="manual-procedimiento"><h3>GPT (ALT) - Metodo IFCC</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. 20 uL</ul><h4>2. Reactivos</h4><ul><li>L-alanina, alfa-cetoglutarato, LDH, NADH</li></ul><h4>3. Procedimiento</h4><p>R1 500 uL + 20 uL muestra. R2 100 uL. Cinetica 340 nm 37C.</p><h4>4. Referencia</h4><p>Hombres menor 41 U/L. Mujeres menor 33 U/L</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (63, 'GPT/ALT - Wiener Lab', '<div class="manual-procedimiento"><h3>GPT (ALT) - Metodo IFCC</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul>Suero. 20 uL</ul><h4>2. Reactivos</h4><ul><li>L-alanina, alfa-cetoglutarato, LDH, NADH</li></ul><h4>3. Procedimiento</h4><p>R1 500 uL + 20 uL muestra. R2 100 uL. Cinetica 340 nm 37C.</p><h4>4. Referencia</h4><p>Hombres menor 41 U/L. Mujeres menor 33 U/L</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (35, 'Bilirrubina (D,I,T) - Wiener Lab', '<div class="manual-procedimiento"><h3>Bilirrubina Total - Wiener Lab DPD</h3><p><strong>Proveedor:</strong> Wiener Lab (Argentina)</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Proteger de luz (degradacion hasta 50%)</li><li>7 dias 2-8C protegida de luz</li></ul><h4>2. Reactivos</h4><ul><li>Sal diclorfenildiazonio (DPD), HCl, reactivo blanco muestra</li><li>2-10C. Reactivo trabajo estable 21 dias refrigerado</li></ul><h4>3. Equipo</h4><p>546 nm</p><h4>4. Procedimiento</h4><p>Bilirrubina indirecta liberada con surfactante. Reaccion DPD. Lectura 546 nm.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (30, 'Acido Urico - Human', '<div class="manual-procedimiento"><h3>Acido Urico - Metodo Enzimatico Uricasa</h3><p><strong>Proveedor:</strong> Human / Wiener</p><h4>1. Muestra</h4><ul>Suero o plasma. 10 uL</ul><h4>2. Reactivos</h4><ul><li>Uricasa, peroxidasa, 4-AF, 2,4-diclorofenol. 2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 1 ml + 10 uL muestra. 37C 5-10 min. Lectura 505-546 nm.</p><h4>4. Referencia</h4><p>Hombres 3,5-7,2 mg/dL. Mujeres 2,6-6,0 mg/dL</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (82, 'VDRL-RPR - Wiener Lab', '<div class="manual-procedimiento"><h3>VDRL-RPR - Prueba Sifilis</h3><p><strong>Proveedor:</strong> Wiener / Human / Randox</p><h4>1. Muestra</h4><ul><li>Suero o plasma inactivado 56C 30 min</li><li>No usar hemolizadas ni lipemicas</li></ul><h4>2. Reactivos</h4><ul><li>Antigeno cardiolipina en particulas de carbon/latex</li><li>2-8C. Homogeneizar antes de usar</li></ul><h4>3. Procedimiento</h4><ol><li>50 uL suero en placa</li><li>Agregar 1 gota antigeno</li><li>Rotar 8 min a 180 rpm</li><li>Lectura: agregacion visible = reactivo</li></ol><h4>4. Interpretacion</h4><p>Agregacion = positivo. Sin agregacion = no reactivo</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (47, 'Hb. Glicosilada - Human', '<div class="manual-procedimiento"><h3>Hb Glicosilada - HPLC / Inmunoinhibicion</h3><p><strong>Proveedor:</strong> Human / Wiener / Randox</p><h4>1. Muestra</h4><ul><li>Sangre EDTA. 5 uL sangre total o hemolisado</li><li>Estable 7 dias 2-8C</li></ul><h4>2. Reactivos</h4><ul><li>Reactivo turbidimetrico o HPLC. Tipico: inhibicion inmunologica</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Hemolisado + reactivo. Incubar. Lectura 415-505 nm o HPLC.</p><h4>4. Referencia</h4><p>Menor 5,7% normal. 5,7-6,4% prediabetes. 6,5% o mas diabetes</p></div>', 0);

-- Manuales adicionales desde insertos (Wiener, SpinReact, Linear, Diasys)
INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (48, 'LDH - Wiener Lab', '<div class="manual-procedimiento"><h3>LDH - Metodo UV Enzimatico</h3><p><strong>Proveedor:</strong> Wiener Lab (Argentina)</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis (LDH eritrocitaria alta)</li><li>Estable 3 dias 2-8C. Congelar para periodos mayores</li></ul><h4>2. Reactivos</h4><ul><li>Piruvato, NADH, buffer. Metodo UV cinetico</li><li>2-10C hasta caducidad</li></ul><h4>3. Equipo</h4><p>Espectrofotometro 340 nm. 37C</p><h4>4. Procedimiento</h4><p>Lectura cinetica 340 nm. Decrecimiento absorbancia proporcional a actividad LDH.</p><h4>5. Referencia</h4><p>Adultos 240-480 U/L (valores segun metodo). Revisar inserto o establecer rango propio.</p><h4>6. Significado clinico</h4><p>Elevada en infarto cardiaco, hepatopatias, hemolisis, miopatias.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (50, 'Urea - Linear', '<div class="manual-procedimiento"><h3>Urea/BUN - Linear Clonatest Ureasa/GLDH</h3><p><strong>Proveedor:</strong> Linear Chemicals (Espana). Ref KR10382</p><h4>1. Muestra</h4><ul><li>Suero o plasma heparinizado. Sin fluoruro ni oxalato</li><li>Estable 7 dias 2-8C. Congelar para mayor tiempo</li><li>Orina: diluir 1:50 con agua destilada, multiplicar x50</li></ul><h4>2. Reactivos</h4><ul><li><strong>R1:</strong> TRIS 125 mmol/L pH 7,4, 2-cetoglutarato 10 mmol/L, ureasa 140 U/mL, GLDH 120 U/mL</li><li><strong>R2:</strong> NADH 1,50 mmol/L. Listos para uso</li><li>2-8C. Estable en analizador 30 dias. Desechar si A340 menor 1,100 vs agua</li></ul><h4>3. Procedimiento</h4><p>Metodo cinetico UV 340 nm. Calibracion 2 puntos (NaCl 9 g/L + calibrador). Blanco diario.</p><h4>4. Calculo</h4><p>Si mayor 500 mg/dL diluir 1:2 con salina. mg/dL x 0,1665 = mmol/L. mg/dL x 0,467 = BUN.</p><h4>5. Referencia</h4><p>Adultos 15-40 mg/dL (2,5-6,6 mmol/L). Neonatos menor 10 dias: 6,4-53,5 mg/dL. Mayores 60 anos: 17-50 mg/dL.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (44, 'Glicemia - DiaSys', '<div class="manual-procedimiento"><h3>Glucosa GOD-PAP - DiaSys Glucose GOD FS</h3><p><strong>Proveedor:</strong> DiaSys (Alemania)</p><h4>1. Muestra</h4><ul><li>Suero o plasma heparina. Separar celulas max 1 h postextraccion</li><li>Con inhibitor glucolitico: 2 dias 20-25C, 7 dias 4-8C</li><li>Sin inhibitor: 8 h 25C, 72 h 4C</li></ul><h4>2. Reactivos</h4><ul><li>Fosfato pH 7,5 250 mmol/L, fenol 5 mmol/L, 4-aminoantipirina 0,5 mmol/L, GOD 10 kU/L, POD 1 kU/L</li><li>2-8C. Estabilidad abierto 18 meses. No congelar. Proteger de luz. Contiene azida sodio</li></ul><h4>3. Equipo</h4><p>respons 910 u otro: 508/700 nm, 37C, endpoint. Muestra 2 uL, Reactivo 180 uL.</p><h4>4. Procedimiento</h4><p>Calibracion lineal. Glucosa = A muestra / A calibrador x Conc calibrador.</p><h4>5. Rango y referencia</h4><p>Lineal 0,43-500 mg/dL. Ayuno adultos 60-95 mg/dL (3,3-5,3 mmol/L). Ninos ayuno 60-99 mg/dL.</p><h4>6. Interferencias</h4><p>Acido ascorbico, N-acetilcisteina, acetaminofeno, metamizol pueden dar resultados falsamente bajos.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (30, 'Acido Urico - Wiener Lab', '<div class="manual-procedimiento"><h3>Acido Urico - Wiener Lab Metodo Uricasa</h3><p><strong>Proveedor:</strong> Wiener Lab (Argentina)</p><h4>1. Muestra</h4><ul><li>Suero o plasma. 10 uL</li><li>Evitar hemolisis y lipemia</li></ul><h4>2. Reactivos</h4><ul><li>Uricasa, peroxidasa, 4-aminoantipirina, 2,4-diclorofenol</li><li>2-10C hasta caducidad</li></ul><h4>3. Procedimiento</h4><p>R1 + muestra. Incubar 37C 5-10 min. Lectura 505-546 nm.</p><h4>4. Referencia</h4><p>Hombres 3,5-7,2 mg/dL. Mujeres 2,6-6,0 mg/dL</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (36, 'Creatinina - SpinReact', '<div class="manual-procedimiento"><h3>Creatinina - SpinReact Metodo Enzimatico Trinder</h3><p><strong>Proveedor:</strong> SpinReact (Espana)</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis</li><li>Estable 7 dias 2-8C</li></ul><h4>2. Reactivos</h4><ul><li><strong>Principio:</strong> Creatinasa, sarcosina oxidasa, peroxidasa. Trinder colorimetrico</li><li>2-8C hasta caducidad</li></ul><h4>3. Equipo</h4><p>Espectrofotometro 505-546 nm. 37C</p><h4>4. Procedimiento</h4><p>Metodo endpoint o cinetico segun aplicacion analizador. Calibracion con patron.</p><h4>5. Referencia</h4><p>Hombres 0,7-1,3 mg/dL. Mujeres 0,6-1,1 mg/dL. Metodo enzimatico evita interferencias del Jaffe con proteinas y cetonas.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (49, 'Trigliceridos - SpinReact', '<div class="manual-procedimiento"><h3>Trigliceridos - SpinReact GPO-POD TG-LIQ</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref TKBSIS49</p><h4>1. Muestra</h4><ul><li>Suero. Ayuno 12 h. Evitar lipemia severa</li><li>10 uL muestra</li></ul><h4>2. Reactivos</h4><ul><li>Metodo GPO-POD: lipasa, glicerol kinasa, GPO, peroxidasa, 4-AF, 4-clorofenol</li><li>2-8C. Listo para uso</li></ul><h4>3. Procedimiento</h4><p>R1 + muestra. 37C 10 min. Lectura 505 nm.</p><h4>4. Rango y referencia</h4><p>Lineal hasta 1200 mg/dL. Hombres 40-160 mg/dL. Mujeres 35-135 mg/dL. Normal menor 150 mg/dL. Alto 150-499. Muy alto 500 o mas.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (209, 'Lipasa - SpinReact', '<div class="manual-procedimiento"><h3>Lipasa - SpinReact DGGR</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref spbeis54</p><h4>1. Muestra</h4><ul><li>Suero. Tubo sin anticoagulante o heparina</li><li>Evitar lipemia y hemolisis severa</li></ul><h4>2. Reactivos</h4><ul><li>1,2-O-dilauril-rac-glicerol-3-glutaril-(6-metilresorufina)-eter (DGGR), lipasa pancreatica</li><li>2-8C hasta caducidad</li></ul><h4>3. Procedimiento</h4><p>Metodo colorimetrico enzimatico. Lectura 580 nm (resorufina). 37C.</p><h4>4. Referencia</h4><p>13-60 U/L. Elevada en pancreatitis aguda, obstruccion biliar, enfermedad pancreaticas.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (43, 'GGT - Linear', '<div class="manual-procedimiento"><h3>GGT - Linear Chemicals</h3><p><strong>Proveedor:</strong> Linear Chemicals (Espana). Ref CT10192</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis</li><li>Estable varios dias 2-8C</li></ul><h4>2. Reactivos</h4><ul><li>L-gamma-glutamil-3-carboxi-4-nitroanilida, glicilglicina. Metodo cinetico IFCC</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 405 nm. 37C.</p><h4>4. Referencia</h4><p>Hombres menor 55 U/L. Mujeres menor 38 U/L. Elevada en hepatopatias, colestasis, induccion farmacologica.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (42, 'GOT/AST - Linear', '<div class="manual-procedimiento"><h3>GOT (AST) - Linear Reitman-Frankel</h3><p><strong>Proveedor:</strong> Linear Chemicals (Espana). Ref KR10160</p><h4>1. Muestra</h4><ul><li>Suero. Evitar hemolisis (AST eritrocitaria)</li></ul><h4>2. Reactivos</h4><ul><li>L-aspartato, alfa-cetoglutarato, LDH, NADH. Metodo colorimetrico Reitman-Frankel con DNPH</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura 505-540 nm. 37C. Cinetica o endpoint segun protocolo.</p><h4>4. Referencia</h4><p>Hombres menor 40 U/L. Mujeres menor 32 U/L.</p></div>', 0);

-- Manuales adicionales desde insertos SpinReact (Wiener, SpinReact, BioSystems, Human, Biolabo, DiaSys)
INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (31, 'Albumina - SpinReact', '<div class="manual-procedimiento"><h3>Albumina - SpinReact Verde Bromocresol</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001020-1001023</p><h4>1. Muestra</h4><ul><li>Suero o plasma libre de hemolisis</li><li>Estable 1 mes 2-8C o 1 semana 15-25C</li></ul><h4>2. Reactivos</h4><ul><li>Verde bromocresol pH 4,2 0,12 mmol/L. ALBUMIN CAL patron 5 g/dL</li><li>2-8C. Listo para uso. Desechar si blanco A630 mayor 0,40</li></ul><h4>3. Procedimiento</h4><p>RT 1 mL + patron o muestra 5 uL. Incubar 5 min 37C o 10 min 15-25C. Lectura 630 nm (600-650). Color estable 1 h.</p><h4>4. Calculo</h4><p>Albumina = (A muestra - A blanco) / (A patron - A blanco) x 5 g/dL. g/dL x 144,9 = umol/L</p><h4>5. Referencia</h4><p>3,5-5,0 g/dL. Lineal hasta 6 g/dL; si mayor diluir 1/2 con NaCl 9 g/L.</p><h4>6. Interferencias</h4><p>Bilirrubina 110 mg/L, Hb 1 g/L, lipemia 10 g/L pueden interferir.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (50, 'Urea - SpinReact', '<div class="manual-procedimiento"><h3>Urea UV - SpinReact Ureasa-GLDH</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001332-1001333</p><h4>1. Muestra</h4><ul><li>Suero o plasma heparinizado. No fluoruro ni sales amonio</li><li>Orina: diluir 1/50 con agua, multiplicar x50. pH menor 4 para evitar bacterias</li><li>Estable 5 dias 2-8C</li></ul><h4>2. Reactivos</h4><ul><li><strong>R1:</strong> TRIS pH 7,8 80 mmol/L, alfa-cetoglutarato 6 mmol/L</li><li><strong>R2:</strong> Ureasa 3750 U/L, GLDH 6000 U/L, NADH 0,32 mmol/L</li><li>RT: disolver R2 en R1. Estable 6 sem 2-8C o 7 dias 15-25C. Desechar si blanco A340 menor 1,00</li></ul><h4>3. Procedimiento</h4><p>RT 1 mL + 10 uL muestra. Leer A1 a 30 s y A2 a 90 s. delta A = A1 - A2. 340 nm, 37C.</p><h4>4. Calculo</h4><p>Urea = delta A muestra / delta A patron x 50 mg/dL. mg/dL x 0,1665 = mmol/L. mg/dL x 0,466 = BUN.</p><h4>5. Referencia</h4><p>Suero 15-45 mg/dL (2,49-7,49 mmol/L). Orina 20-35 g/24h. Si mayor 530 diluir 1/2.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (32, 'Proteinas Totales - SpinReact', '<div class="manual-procedimiento"><h3>Proteinas Totales - SpinReact Biuret</h3><p><strong>Proveedor:</strong> SpinReact (Espana)</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis severa</li></ul><h4>2. Reactivos</h4><ul><li>Metodo Biuret colorimetrico. Cu2+ con enlaces peptidicos</li><li>2-8C hasta caducidad</li></ul><h4>3. Procedimiento</h4><p>Lectura 546 nm. 37C. Endpoint.</p><h4>4. Referencia</h4><p>6,0-8,0 g/dL. Albumina 3,5-5,0. Globulinas por diferencia.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (36, 'Creatinina Jaffe - SpinReact', '<div class="manual-procedimiento"><h3>Creatinina - SpinReact Metodo Jaffe Cinetico</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001110-1001113</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis</li><li>Estable 7 dias 2-8C</li></ul><h4>2. Reactivos</h4><ul><li>Acido picrico en medio alcalino. Metodo Jaffe cinetico para reducir interferencias</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 505-546 nm. 37C. Lecturas a 20 s y 80 s para delta A.</p><h4>4. Referencia</h4><p>Hombres 0,7-1,3 mg/dL. Mujeres 0,6-1,1 mg/dL.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (44, 'Glicemia - SpinReact', '<div class="manual-procedimiento"><h3>Glucosa GOD-POD - SpinReact Trinder / LQ</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 41010-41013, 1001190-1001191</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Tubo sin anticoagulante o heparina</li></ul><h4>2. Reactivos</h4><ul><li>GOD-POD (Glucosa oxidasa - Peroxidasa). Trinder: 4-AF + fenol. LQ: liquido listo</li><li>2-8C. Proteger de luz</li></ul><h4>3. Procedimiento</h4><p>R1 + muestra. Incubar 37C 5-10 min. Lectura 505 nm.</p><h4>4. Referencia</h4><p>Ayuno 70-100 mg/dL (3,9-5,6 mmol/L).</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (30, 'Acido Urico - SpinReact', '<div class="manual-procedimiento"><h3>Acido Urico - SpinReact Uricasa-POD</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001010-1001011, 41000-41002</p><h4>1. Muestra</h4><ul><li>Suero o plasma. 10 uL</li></ul><h4>2. Reactivos</h4><ul><li>Uricasa, peroxidasa, 4-AF, 2,4-diclorofenol. Enzimatico colorimetrico</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 + muestra. 37C 5-10 min. Lectura 505-546 nm.</p><h4>4. Referencia</h4><p>Hombres 3,5-7,2 mg/dL. Mujeres 2,6-6,0 mg/dL</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (3, 'Hemoglobina - SpinReact', '<div class="manual-procedimiento"><h3>Hemoglobina - SpinReact Drabkin</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001230</p><h4>1. Muestra</h4><ul><li>Sangre total con EDTA o heparina. Hemolisar con reactivo Drabkin</li></ul><h4>2. Reactivos</h4><ul><li>Ferricianuro, cianuro. Metodo Drabkin colorimetrico. CN-metaHb</li><li>2-8C. Ref 1001230: 4x5 mL</li></ul><h4>3. Procedimiento</h4><p>Dilucion sangre + reactivo. Incubar. Lectura 540 nm.</p><h4>4. Referencia</h4><p>Hombres 13,5-17,5 g/dL. Mujeres 12,0-15,5 g/dL.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (42, 'GOT/AST - SpinReact', '<div class="manual-procedimiento"><h3>GOT (AST) - SpinReact IFCC UV</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001160-1001162</p><h4>1. Muestra</h4><ul><li>Suero. Evitar hemolisis (AST intraeritrocitaria)</li></ul><h4>2. Reactivos</h4><ul><li>L-aspartato, alfa-cetoglutarato, LDH, NADH. Metodo IFCC cinetico UV</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 340 nm. 37C.</p><h4>4. Referencia</h4><p>Hombres menor 40 U/L. Mujeres menor 32 U/L</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (41, 'GPT/ALT - SpinReact', '<div class="manual-procedimiento"><h3>GPT (ALT) - SpinReact IFCC UV</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001170-1001172</p><h4>1. Muestra</h4><ul><li>Suero. Evitar hemolisis</li></ul><h4>2. Reactivos</h4><ul><li>L-alanina, alfa-cetoglutarato, LDH, NADH. Metodo IFCC cinetico UV</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 340 nm. 37C.</p><h4>4. Referencia</h4><p>Hombres menor 41 U/L. Mujeres menor 33 U/L</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (43, 'GGT - SpinReact', '<div class="manual-procedimiento"><h3>GGT - SpinReact Carboxi-4-nitroanilida</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001185-1001187</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis</li></ul><h4>2. Reactivos</h4><ul><li>L-gamma-glutamil-3-carboxi-4-nitroanilida, glicilglicina. IFCC</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 405 nm. 37C.</p><h4>4. Referencia</h4><p>Hombres menor 55 U/L. Mujeres menor 38 U/L</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (48, 'LDH - SpinReact', '<div class="manual-procedimiento"><h3>LDH - SpinReact DGKC Piruvato UV</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001260</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis (LDH eritrocitaria muy alta)</li></ul><h4>2. Reactivos</h4><ul><li>Piruvato, NADH. Metodo DGKC cinetico UV</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 340 nm. 37C. Decrecimiento absorbancia.</p><h4>4. Referencia</h4><p>Adultos 240-480 U/L (rango segun poblacion). Elevada en IAM, hepatopatias, hemolisis.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (29, 'Amilasa - SpinReact', '<div class="manual-procedimiento"><h3>Amilasa - SpinReact CNPG3 LQ</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 41201-41202</p><h4>1. Muestra</h4><ul><li>Suero o orina. Suero: evitar lipemia</li></ul><h4>2. Reactivos</h4><ul><li>2-cloro-4-nitrofenil-maltoheptaosido (CNPG3). Enzimatico colorimetrico</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 405 nm. 37C.</p><h4>4. Referencia</h4><p>Suero 28-100 U/L. Amilasuria variable. Elevada en pancreatitis, patologia pancreaticas.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (39, 'Fosfatasa Alcalina - SpinReact', '<div class="manual-procedimiento"><h3>Fosfatasa Alcalina - SpinReact DGKC / IFCC</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001130, 41240-41246</p><h4>1. Muestra</h4><ul><li>Suero. Evitar hemolisis</li></ul><h4>2. Reactivos</h4><ul><li>DGKC: p-nitrofenilfosfato. IFCC: AMP buffer. Metodo cinetico</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 405 nm. 37C.</p><h4>4. Referencia</h4><p>Adultos 40-150 U/L. Ninos y adolescentes mayor (crecimiento oseo). Elevada en colestasis, enfermedad osea.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (68, 'CK - SpinReact', '<div class="manual-procedimiento"><h3>CK - SpinReact NAC UV</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001050, 41250</p><h4>1. Muestra</h4><ul><li>Suero. Evitar hemolisis. Muestra estable 2-4 h a 25C; 24 h 2-8C</li></ul><h4>2. Reactivos</h4><ul><li>N-acetilcisteina (NAC), creatina fosfato, glucosa, ADP, hexoquinasa, G6PDH. Metodo UV cinetico</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura cinetica 340 nm. 37C.</p><h4>4. Referencia</h4><p>Hombres 39-308 U/L. Mujeres 26-192 U/L. Elevada en IAM, miopatias, rabdomiolisis.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (69, 'CK-MB - SpinReact', '<div class="manual-procedimiento"><h3>CK-MB - SpinReact Inmunoinhibicion UV</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001054-1001055, 41254</p><h4>1. Muestra</h4><ul><li>Suero. Igual que CK</li></ul><h4>2. Reactivos</h4><ul><li>Anti-CK-M inhibe subunidad M. Mide actividad CK-B (CK-MB + CK-BB)</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Inhibicion + medicion CK restante. UV cinetico 340 nm.</p><h4>4. Referencia</h4><p>CK-MB menor 5% de CK total o menor 25 U/L. Elevada en IAM.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (37, 'Colinesterasa - SpinReact', '<div class="manual-procedimiento"><h3>Colinesterasa - SpinReact Butiriltiocolina</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001100, 41210</p><h4>1. Muestra</h4><ul><li>Suero. Evitar hemolisis</li></ul><h4>2. Reactivos</h4><ul><li>Butiriltiocolina, ditiotreitol. Metodo cinetico colorimetrico</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura 405 nm. 37C.</p><h4>4. Referencia</h4><p>5300-12900 U/L (valores segun metodo). Disminuida en intoxicacion organofosforados, hepatopatia.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (38, 'Colesterol - SpinReact', '<div class="manual-procedimiento"><h3>Colesterol - SpinReact CHOD-POD</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001091-1001092, 41019-41022</p><h4>1. Muestra</h4><ul><li>Suero. Ayuno 12 h. 10 uL</li></ul><h4>2. Reactivos</h4><ul><li>Esterasa, oxidasa, peroxidasa, 4-AF, fenol. Metodo CHOD-POD</li><li>2-8C. Listo para uso</li></ul><h4>3. Procedimiento</h4><p>R1 + muestra. 37C 10 min. Lectura 505 nm.</p><h4>4. Referencia</h4><p>Deseable menor 200 mg/dL. Limite 200-239. Alto 240 o mas.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (60, 'C-HDL - SpinReact', '<div class="manual-procedimiento"><h3>HDL Colesterol - SpinReact Directo Enzimatico</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001096-1001098</p><h4>1. Muestra</h4><ul><li>Suero. Ayuno 12 h</li></ul><h4>2. Reactivos</h4><ul><li>Metodo directo enzimatico. No requiere precipitacion previa</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 + R2 + muestra. Lectura 505 nm. 37C.</p><h4>4. Referencia</h4><p>Hombres mayor 40 mg/dL. Mujeres mayor 50 mg/dL. Factor protector cardiovascular.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (61, 'C-LDL - SpinReact', '<div class="manual-procedimiento"><h3>LDL Colesterol - SpinReact Directo Enzimatico</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 41023-41024</p><h4>1. Muestra</h4><ul><li>Suero. Ayuno 12 h</li></ul><h4>2. Reactivos</h4><ul><li>Metodo directo. Esterasa, oxidasa, catalasa, peroxidasa. Sin centrifugacion</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>R1 + R2 + muestra. 505 nm. 37C.</p><h4>4. Referencia</h4><p>Optimo menor 100 mg/dL. Casi optimo 100-129. Limite 130-159. Alto 160-189. Muy alto 190 o mas.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (35, 'Bilirrubina - SpinReact', '<div class="manual-procedimiento"><h3>Bilirrubina Total - SpinReact DPD</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001046</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Proteger de luz (degradacion hasta 50%)</li><li>Estable 48 h 2-8C protegida de luz</li></ul><h4>2. Reactivos</h4><ul><li>Sal diclorfenildiazonio (DPD). Colorimetrico. Bilirrubina + DPD = azocompuesto rojo</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Lectura 546 nm. Acido.</p><h4>4. Referencia</h4><p>Total menor 1,0 mg/dL. Neonatos valores mas altos. Lineal hasta 20 mg/dL; diluir si mayor.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (24, 'APTT - SpinReact', '<div class="manual-procedimiento"><h3>APTT - SpinReact Tiempo Tromboplastina Parcial Activada</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1709201</p><h4>1. Muestra</h4><ul><li>Plasma citratado 3,2% o 3,8%. Relacion 9:1 sangre:citrato</li><li>Centrifugar 15 min. Analizar en 4 h</li></ul><h4>2. Reactivos</h4><ul><li>Activador (kaolin, etc.) + fosfolipidos. 5x4 mL</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>37C. Plasma + reactivo activador. Incubar. Agregar CaCl2. Medir tiempo coagulacion.</p><h4>4. Referencia</h4><p>25-35 s (establecer rango con plasma normal). Alargado en deficit factores via intrinseca, anticoagulantes.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (23, 'T. Protrombina - SpinReact', '<div class="manual-procedimiento"><h3>Tiempo de Protrombina / INR - SpinReact PT Test</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1709222-1709225</p><h4>1. Muestra</h4><ul><li>Plasma citratado 3,2%. Relacion 9:1</li></ul><h4>2. Reactivos</h4><ul><li>Tromboplastina + Ca. Sensible a factores VII, X, V, II, fibrinogeno</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Plasma 37C + tromboplastina. Medir tiempo. Calcular INR = (PT paciente/PT normal)^ISI.</p><h4>4. Referencia</h4><p>INR 2-3 anticoagulacion oral. PT 11-15 s (segun reactivo).</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (7, 'Fibrinogeno - SpinReact', '<div class="manual-procedimiento"><h3>Fibrinogeno - SpinReact Clauss</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1709211</p><h4>1. Muestra</h4><ul><li>Plasma citratado. Centrifugar</li></ul><h4>2. Reactivos</h4><ul><li>Trombina. Metodo Clauss: tiempo coagulacion inversamente proporcional a fibrinogeno</li><li>8x2 mL + 1x100 mL diluyente</li></ul><h4>3. Procedimiento</h4><p>Dilucion plasma + trombina. Medir tiempo. Calibracion con patron.</p><h4>4. Referencia</h4><p>200-400 mg/dL. Bajo en coagulacion intravascular, afibrinogenemia.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (14, 'D-Dimeros - SpinReact', '<div class="manual-procedimiento"><h3>D-Dimeros - SpinReact</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1709231</p><h4>1. Muestra</h4><ul><li>Plasma citratado. Centrifugar. No hemolizado</li></ul><h4>2. Reactivos</h4><ul><li>Metodo inmunoturbidimetrico. Anticuerpos anti-D-dímero</li><li>2x10 mL + 2x10 mL. 2-8C</li></ul><h4>3. Procedimiento</h4><p>Calibracion obligatoria. Muestra + reactivo. Lectura turbidimetrica.</p><h4>4. Referencia</h4><p>Menor 500 ng/mL o 0,5 mg/L (según unidades). Elevado en TEP, CID, trombosis.</p></div>', 0);

-- Electrolitos - Quimica humeda / colorimetrica (SpinReact)
INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (54, 'Sodio - SpinReact', '<div class="manual-procedimiento"><h3>Sodio - SpinReact ONPG Colorimetrico</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001387</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis (libera K intracellular)</li></ul><h4>2. Reactivos</h4><ul><li>Metodo ONPG colorimetrico. 1 inserto por analito (quimica humeda)</li><li>2-8C hasta caducidad</li></ul><h4>3. Procedimiento</h4><p>R1 + R2 + muestra. Lectura segun protocolo analizador.</p><h4>4. Referencia</h4><p>136-145 mmol/L. Alternativa: ISE Na/K/Cl cubre Na, K y Cl en 1 inserto (autoanalizadores).</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (52, 'Potasio - SpinReact', '<div class="manual-procedimiento"><h3>Potasio - SpinReact Pyruvate Kinase</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001397</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis (K elevado)</li></ul><h4>2. Reactivos</h4><ul><li>Metodo enzimatico Pyruvate Kinase. Colorimetrico</li><li>2-8C. 1x60 mL + 1x15 mL</li></ul><h4>3. Procedimiento</h4><p>R1 + R2 + muestra. Lectura segun protocolo.</p><h4>4. Referencia</h4><p>3,5-5,0 mmol/L. Alternativa ISE: 1 inserto Na/K/Cl cubre los 3.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (53, 'Cloro - SpinReact', '<div class="manual-procedimiento"><h3>Cloruro - SpinReact Thiocianato-Hg</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001360</p><h4>1. Muestra</h4><ul><li>Suero o plasma</li></ul><h4>2. Reactivos</h4><ul><li>Metodo Thiocianato-Hg colorimetrico. 2x150 mL</li><li>2-8C</li></ul><h4>3. Procedimiento</h4><p>Reactivo + muestra. Lectura fotometrica.</p><h4>4. Referencia</h4><p>98-106 mmol/L. Alternativa ISE: Na/K/Cl cubre Cl con Na y K.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (57, 'Calcio - SpinReact', '<div class="manual-procedimiento"><h3>Calcio - SpinReact Arsenazo III</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001065</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Separar de hematies pronto. No oxalato ni EDTA</li><li>Orina 24h: contenedor libre de calcio, añadir 10 mL HNO3 50%. Diluir 1/2, multiplicar x2</li><li>Estable 10 dias 2-8C</li></ul><h4>2. Reactivos</h4><ul><li>Arsenazo III, tampon imidazol pH 6,5. CALCIUM CAL patron 10 mg/dL</li><li>2-8C. Material plastico. Lavar vidrio con HNO3 diluido si se usa</li></ul><h4>3. Procedimiento</h4><p>R 1 mL + patron o muestra 10 uL. Incubar 2 min 37C. Lectura 650 nm. Color estable 1 h.</p><h4>4. Calculo</h4><p>Calcio = (A muestra - A blanco) / (A patron - A blanco) x 10 mg/dL. mg/dL x 0,25 = mmol/L.</p><h4>5. Referencia</h4><p>Adultos 8,5-10,5 mg/dL (2,1-2,6 mmol/L). Ninos 10-12. Neonatos 8-13. Orina 24h 50-300 mg.</p><h4>6. Interferencias</h4><p>Trigliceridos menor 1,25 g/L no interfieren. No usar detergentes con quelantes en material.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (55, 'Magnesio - SpinReact', '<div class="manual-procedimiento"><h3>Magnesio - SpinReact Xylidyl Blue</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001285-1001286</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Evitar hemolisis</li></ul><h4>2. Reactivos</h4><ul><li>Xylidyl Blue (Xilidilo Azul). Colorimetrico</li><li>2x50 mL o 2x150 mL. 2-8C</li></ul><h4>3. Procedimiento</h4><p>Reactivo + muestra. Lectura fotometrica.</p><h4>4. Referencia</h4><p>1,7-2,2 mg/dL (0,7-0,9 mmol/L). Disminuido en hipomagnesemia, diuresis, malabsorcion.</p></div>', 0);

INSERT INTO dom_manuals (prianacategoria_id, tittle, `manual`, deleted) VALUES (56, 'Fosforo - SpinReact', '<div class="manual-procedimiento"><h3>Fosforo - SpinReact Fosfomolibdato UV</h3><p><strong>Proveedor:</strong> SpinReact (Espana). Ref 1001154-1001155</p><h4>1. Muestra</h4><ul><li>Suero o plasma. Separar pronto. Evitar hemolisis</li></ul><h4>2. Reactivos</h4><ul><li>Fosfomolibdato. Metodo UV colorimetrico</li><li>2x50 mL o 2x150 mL. 2-8C</li></ul><h4>3. Procedimiento</h4><p>Reactivo + muestra. Lectura UV.</p><h4>4. Referencia</h4><p>Ninos 4,0-7,0 mg/dL. Adultos 2,5-5,0 mg/dL. Elevado en insuficiencia renal, hipoparatiroidismo.</p></div>', 0);
