<form method="get" action="<?= esc($form_action) ?>" class="row g-2 align-items-end mb-4">
<div class="col-md-2"><label class="form-label small mb-0">Desde</label><input type="date" name="start" class="form-control form-control-sm" value="<?= esc($startDate) ?>"></div>
<div class="col-md-2"><label class="form-label small mb-0">Hasta</label><input type="date" name="end" class="form-control form-control-sm" value="<?= esc($endDate) ?>"></div>
<div class="col-md-3"><label class="form-label small mb-0">Usuario</label><select name="person_id" class="form-select form-select-sm"><option value="0">Todos</option><?php foreach (($empleados ?? []) as $em): ?><option value="<?= (int)$em['person_id'] ?>" <?= ((int)($person_id ?? 0)===(int)$em['person_id'])?'selected':'' ?>><?= esc($em['nombre']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label class="form-label small mb-0">Insumo</label><select name="reactivo_id" class="form-select form-select-sm"><option value="0">Todos</option><?php foreach (($insumos ?? []) as $ins): ?><option value="<?= (int)$ins['reactivo_id'] ?>" <?= ((int)($reactivo_id ?? 0)===(int)$ins['reactivo_id'])?'selected':'' ?>><?= esc($ins['nombre']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-2"><label class="form-label small mb-0">Tipo</label><select name="tipo" class="form-select form-select-sm"><option value="">Entrada y salida</option><option value="entrada" <?= ($tipo??'')==='entrada'?'selected':'' ?>>Entrada</option><option value="salida" <?= ($tipo??'')==='salida'?'selected':'' ?>>Salida</option></select></div>
<div class="col-12"><button type="submit" class="btn btn-primary btn-sm">Filtrar</button></div>
</form>
<div class="table-responsive"><table class="table table-sm table-striped"><thead><tr><th>Fecha</th><th>Insumo</th><th>Tipo</th><th>Cantidad</th><th>Saldo</th><th>Lote</th><th>Orden</th><th>Usuario</th><th>Obs.</th></tr></thead><tbody><?php foreach(($rows??[]) as $m): ?><tr><td><?= esc($m['fecha']??'') ?></td><td><?= esc($m['reactivo_nombre']??'') ?></td><td><?= esc($m['tipo']??'') ?></td><td><?= esc($m['cantidad']??'') ?></td><td><?= isset($m['saldo_acumulado'])?esc($m['saldo_acumulado']):'-' ?></td><td><?= esc($m['codigo_lote']??'') ?></td><td><?php $rid=(int)($m['registro_id']??0); if($rid>0): ?><a href="<?= site_url('registers/insumos/'.$rid) ?>"><?= esc(($m['numero_orden']??'')?:('#'.$rid)) ?></a><?php endif; ?></td><td><?= esc(trim($m['usuario_nombre']??'')?:'-') ?></td><td><?= esc($m['observaciones']??'') ?></td></tr><?php endforeach; if(empty($rows)): ?><tr><td colspan="9" class="text-center text-muted">Sin movimientos</td></tr><?php endif; ?></tbody></table></div>
